name: Build Windows

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Windows
    runs-on: windows-latest
    outputs:
      msix-conclusion: ${{ steps.msix-artifact.conclusion }}
      installer-conclusion: ${{ steps.installer-artifact.conclusion }}
    steps:
      - name: 签出仓库
        uses: actions/checkout@v4
    
      - name: 上传产物
        id: binary-artifact
        uses: actions/upload-artifact@v4
        with:
          name: binary
          path: binary/**/*
          compression-level: 9

      - name: 上传 MSIX
        id: msix-artifact
        uses: actions/upload-artifact@v4
        with:
          name: msix
          path: pixez.msix
          compression-level: 9

      - name: 上传 MSIX 安装器
        id: installer-artifact
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: MsixInstaller.exe
          compression-level: 9

      - name: 生成校验和
        shell: pwsh
        run: |-
          Write-Output '### Build Success :rocket:' >> $env:GITHUB_STEP_SUMMARY
          Write-Output '|File|SHA256|' >> $env:GITHUB_STEP_SUMMARY
          Write-Output '|:-|:-:|' >> $env:GITHUB_STEP_SUMMARY
          Write-Output "|[binary](${{ steps.binary-artifact.outputs.artifact-url }})|${{ steps.binary-artifact.outputs.artifact-digest }}|" >> $env:GITHUB_STEP_SUMMARY

          if ('${{ steps.msix-artifact.conclusion }}' -eq 'success') {
            Write-Output "|[msix](${{ steps.msix-artifact.outputs.artifact-url }})|${{ steps.msix-artifact.outputs.artifact-digest }}|" >> $env:GITHUB_STEP_SUMMARY  
          }

          if ('${{ steps.installer-artifact.conclusion }}' -eq 'success') {
            Write-Output "|[installer](${{ steps.installer-artifact.outputs.artifact-url }})|${{ steps.installer-artifact.outputs.artifact-digest }}|" >> $env:GITHUB_STEP_SUMMARY  
          }

  publish:
    name: Publish Release
    runs-on: windows-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    permissions: 
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: 下载所有产物
        uses: actions/download-artifact@v4.1.8

      - name: 发布到 Release
        shell: pwsh
        run: |-
          $Private:Arguments = @('release', 'upload', '${{ github.ref_name }}')
          Compress-Archive -LiteralPath 'binary' -DestinationPath 'windows-x86_64.zip'
          $Private:Arguments += 'windows-x86_64.zip'
          if ('${{ needs.build.outputs.msix-conclusion }}' -eq 'success') {
            Move-Item -LiteralPath 'msix' -Destination 'windows-x86_64.msix'
            $Private:Arguments += 'windows-x86_64.msix'
          }

          if ('${{ needs.build.outputs.installer-conclusion }}' -eq 'success') {
            Move-Item -LiteralPath 'installer' -Destination 'windows-x86_64.exe'
            $Private:Arguments += 'windows-x86_64.exe'
          }
            $Private:Arguments += '--repo'
            $Private:Arguments += '${{ github.repository }}'
          gh $Private:Arguments
